name: CI - Demo backtest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demo-backtest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./naujasbotas
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run demo backtest
        run: |
          python src/run_demo_backtest.py
